development:
  access_key_id: "AKIAIS5ICO5JTWTFSPBA"
  secret_access_key: "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"
  bucket: "ocl"

test:
  access_key_id:
  secret_access_key:
  bucket: "oncall-test"

production:
  access_key_id:
  secret_access_key:
  bucket: "oncall"
